server:
  port: 8093
spring:
  application:
    name: message
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.218.144:3306/loe?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Stn_123456
  rabbitmq:
    host: 47.99.218.144
    port: 5672
    username: root
    password: stn123456
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

eureka:
  client:
    fetch-registry: true  #获取注册实例列表
    register-with-eureka: true #注册到Eureka的注册中心
    service-url:
      defaultZone: http://localhost:8091/eureka #配置注册中心地址